spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.hibernate.ddl-auto=validate

spring.jpa.properties.hibernate.format_sql=false


#Flayway Configuration
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=false
spring.flyway.locations=classpath:db/migration
spring.flyway.sql-migration-prefix=V
spring.flyway.sql-migration-separator=__
spring.flyway.sql-migration-suffixes=.sql
spring.flyway.encoding=UTF-8
spring.flyway.baseline-version=0
spring.flyway.baseline-description=Initial Baseline
spring.flyway.clean-disabled=true
spring.flyway.out-of-order=false
spring.flyway.validate-on-migrate=true

# JWT Configuration
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

#Spring boot multipart configuration
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-request-size=10MB

# Storage
storage.type=${STORAGE_TYPE}
file.upload.dir=${FILE_UPLOAD_DIR:./uploads}
file.upload.max-size=${FILE_MAX_SIZE:10485760}
file.upload.allowed-extensions=${FILE_ALLOWED_EXTENSION:jpg,jpeg,png,webp}

# application.properties
# AWS S3 Configuration
aws.s3.enabled=${AWS_S3_ENABLED}
aws.s3.bucket-name=${AWS_S3_BUCKET_NAME}
aws.s3.region=${AWS_REGION}
aws.access-key-id=
aws.secret-access-key=
aws.s3.endpoint=${AWS_S3_ENDPOINT:}

# CORS
CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}

# ACTUATOR
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never

# Logging
logging.level.root=INFO
logging.level.com.PhotoVault=INFO
logging.level.org.hibernate=ERROR